[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/stay"
  to = "/stay.html"
  status = 200

[[redirects]]
  from = "/experiences"
  to = "/experiences.html"
  status = 200

[[redirects]]
  from = "/dining"
  to = "/dining.html"
  status = 200

[[redirects]]
  from = "/maison"
  to = "/maison.html"
  status = 200

[[redirects]]
  from = "/membership"
  to = "/membership.html"
  status = 200

[[redirects]]
  from = "/journal"
  to = "/journal.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/varena/:splat"
  status = 200